package edu.uncc.vms.domain;

public enum EVENT_STATUS_CODE {

	EVENT_POST_SUCCESS, EVENT_POST_ERROR, 
	EVENT_DELETE_SUCCESS, EVENT_DELETE_ERROR,
	EVENT_VOLUNTEER_SUCCESS, EVENT_VOLUNTEER_ERROR, EVENT_VOLUNTEER_DUPLICATE_ERROR,
	EVENT_EDIT_SUCCESS, EVENT_EDIT_ERROR
}
